server:
  port: ${random.int(8700,8800)}

spring:
  main:
    banner-mode: "off"

  application:
    name: provider-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

spring.zipkin.sender.type: web
spring.sleuth.sampler.probability: 1
spring.zipkin.base-url: http://localhost:9411/