server:
  port: 8763

spring:
  main:
    banner-mode: "off"
  application:
    name: consumer-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 18763
        dashboard: localhost:8748

feign:
  sentinel:
    enabled: true

spring.zipkin.sender.type: web
spring.sleuth.sampler.probability: 1
spring.zipkin.base-url: http://localhost:9411/