server:
  port: 8881
spring:
  cloud:
    compatibility-verifier:
      enabled: false


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/